services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka-kraft
    ports:
      - "9092:9092"   # Para clientes externos
      - "9093:9093"   # Controller
      - "19092:19092" # Para clientes internos (Docker)
    environment:
      KAFKA_KRAFT_MODE: "true"
      # Configuration Kraft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # DOS LISTENERS: uno interno, uno externo
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka-kraft:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Cluster Configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Log Directory
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # Cluster Auto-create ID
      CLUSTER_ID: KFJAOISD29nliqFO

    networks:
      - kafka-network
    volumes:
      - kafka-data:/var/lib/kafka/data
      # - ./kafka-data:/var/lib/kafka/data # se tiene que crear una carpeta local si quieres usar esta opcion

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-kraft:19092
    networks:
      - kafka-network

  # MongoDB 8.0.0
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: covid-db
    networks:
      - kafka-network
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    
  # Mongo Express (UI para MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - kafka-network
    
networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
  flink-checkpoints:
  mongodb-data:
  mongodb-config: